/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {type: 'doc', id: 'getting_started', label: 'Overview'},
    // 'quickstart',
    {
      type: 'category',
      label: 'Development Testing',
      items: [
        {type: 'autogenerated', dirName: 'development_testing'},
      ]
    },
    {
      type: 'category',
      label: 'Deployment Testing',
      link: {type: 'doc', id: 'deployment_testing/deployment_testing'},
      items: [
        {
          type: 'category',
          label: 'Team Cloud',
          link: {type: 'doc', id: 'deployment_testing/deployment_testing'},
          items: [
            {
              type: 'category',
              label: 'Getting Started',
              link: {type: 'doc', id: 'deployment_testing/deployment_testing/getting_started_for_customers'},
              items: [
                {
                  type: 'category',
                  label: 'Data Sources',
                  link: {type: 'doc', id: 'deployment_testing/deployment_testing/getting_started_for_customers/data_sources'},
                  items: [
                    {type: 'autogenerated', dirName: 'deployment_testing/deployment_testing/getting_started_for_customers/data_sources'},
                  ]
                },
                {
                  type: 'category',
                  label: 'Source Control',
                  link: {type: 'doc', id: 'deployment_testing/deployment_testing/getting_started_for_customers/source_control'},
                  items: [
                    {type: 'autogenerated', dirName: 'deployment_testing/deployment_testing/getting_started_for_customers/source_control'},
                  ]
                },
                {
                  type: 'category',
                  label: 'dbt Core/Cloud',
                  link: {type: 'doc', id: 'deployment_testing/deployment_testing/getting_started_for_customers/dbt'},
                  items: [
                    {type: 'autogenerated', dirName: 'deployment_testing/deployment_testing/getting_started_for_customers/dbt'},
                  ]
                },
                {
                  type: 'category',
                  label: 'Data Apps',
                  link: {type: 'doc', id: 'deployment_testing/deployment_testing/getting_started_for_customers/data_apps'},
                  items: [
                    {type: 'autogenerated', dirName: 'deployment_testing/deployment_testing/getting_started_for_customers/data_apps'},
                  ]
                }
              ]
            }
          ]
        },
      ]
    },
    'security',
    'support',
    {
      type: 'category',
      label: 'Enterprise Accounts',
      link: {type: 'doc', id: 'enterprise_accounts'},
      items: [
        {type: 'doc', id: 'enterprise_accounts', label: 'Overview'},
        {
          type: 'category',
          label: 'VPC Deployments',
          link: {type: 'doc', id: 'enterprise_accounts/vpc_deployments'},
          items: [
            {type: 'autogenerated', dirName: 'enterprise_accounts/vpc_deployments'},
          ]
        },
        {
          type: 'category',
          label: 'SSO',
          link: {type: 'doc', id: 'enterprise_accounts/sso'},
          items: [
            {type: 'autogenerated', dirName: 'enterprise_accounts/sso'},
          ]
        },
        {
          type: 'category',
          label: 'Custom Integrations',
          items: [
            {type: 'doc', id: 'enterprise_accounts/custom_integrations/github_vpc', label: 'GitHub'},
          ]
        },
      ]
    },
    {
      type: 'html',
      value: `
      <span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 -0.25rem 0;" />
      <span style="font-size: 0.75rem; color: darkgrey;">Jump to</span>
      `,
      defaultStyle: true, 
    },
    {
      type: 'link',
      label: 'Guides',
      href: '/guides',
    },
    {
      type: 'link',
      label: 'Reference',
      href: '/reference',
    },
  ],
  guides: [
    {
      type: 'category',
      label: 'Overview',
      link: {type: 'doc', id: 'guides'},
      collapsible: false,
      items: [
        {type: 'doc', id: 'guides/os_data_diff', label: 'Open Source Data Diff'},
        {type:'doc', id: 'guides/dbt_advanced_configs'},
        {
          type: 'category',
          label: 'Continuous Integration',
          link: {type: 'doc', id: 'guides/ci'},
          items: [
            {type: 'doc', id: 'guides/ci', label: 'Getting Started'},
            {type: 'autogenerated', dirName: 'guides/ci'},
          ]
        },
        {type: 'doc', id: 'guides/cd'},
        {type: 'doc', id: 'guides/slim_diff'},
      ]
    },
    {
      type: 'html',
      value: `
      <span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 -0.25rem 0;" />
      <span style="font-size: 0.75rem; color: darkgrey;">Jump to</span>
      `,
      defaultStyle: true, 
    },
    {
      type: 'link',
      label: 'Getting Started',
      href: '/',
    },
    {
      type: 'link',
      label: 'Reference',
      href: '/reference',
    },
  ],
  references: [
    {
      type: 'category',
      label: 'Overview',
      link: {type: 'doc', id: 'reference'},
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Open Source',
          link: {type: 'doc', id: 'reference/open_source'},
          collapsible: false,
          items: [
            'reference/open_source/cli',
            {
              type: 'link',
              label: 'Python API',
              href: 'https://data-diff.readthedocs.io/en/latest/python-api.html',
            },
          ]
        },
        {
          type: 'category',
          label: 'Cloud',
          link: {type: 'doc', id: 'reference/cloud'},
          collapsible: false,
          items: [
            'reference/cloud/rest_api',
            // 'reference/cloud/graphql',
            'reference/cloud/datafold-sdk',
          ]
        },
      ]
    },
    {
      type: 'html',
      value: `
      <span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 -0.25rem 0;" />
      <span style="font-size: 0.75rem; color: darkgrey;">Jump to</span>
      `,
      defaultStyle: true, 
    },
    {
      type: 'link',
      label: 'Getting Started',
      href: '/',
    },
    {
      type: 'link',
      label: 'Guides',
      href: '/guides',
    },
  ],
};

module.exports = sidebars;