name: Check links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: setup node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
      with:
        cache: 'npm'

    - name: install dependencies
      run: npm ci

    - name: check internal markdown links
      run: npm run check-links