name: linkcheck
on: [push]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: linkcheck
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://docs.datafold.com/