name: linkcheck

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: filiph/linkcheck@2.0.23
      with:
        arguments: https://docs.datafold.com/